/*
 *
 * CustomerPage constants
 *
 */

export const KEY = 'customerPage';

export const GET_LIST_CUSTOMER = 'app/CustomerPage/GET_LIST_CUSTOMER';
export const GET_LIST_CUSTOMER_SUCCESS =
  'app/CustomerPage/GET_LIST_CUSTOMER_SUCCESS';

export const GET_LIST_CUSTOMER_ERROR =
  'app/CustomerPage/GET_LIST_CUSTOMER_ERROR';

export const GET_OPTIONS_CUSTOMER_REFERENCE =
  'app/CustomerPage/GET_OPTIONS_CUSTOMER_REFERENCE';

export const GET_OPTIONS_CUSTOMER_REFERENCE_SUCCESS =
  'app/CustomerPage/GET_OPTIONS_CUSTOMER_REFERENCE_SUCCESS';

export const GET_OPTIONS_CUSTOMER_REFERENCE_ERROR =
  'app/CustomerPage/GET_OPTIONS_CUSTOMER_REFERENCE_ERROR';

export const GET_OPTIONS_CREATED_BY = 'app/CustomerPage/GET_OPTIONS_CREATED_BY';

export const GET_OPTIONS_CREATED_BY_SUCCESS =
  'app/CustomerPage/GET_OPTIONS_CREATED_BY_SUCCESS';

export const GET_OPTIONS_CREATED_BY_ERROR =
  'app/CustomerPage/GET_OPTIONS_CREATED_BY_ERROR';

export const ADD_CUSTOMER = 'app/CustomerPage/ADD_CUSTOMER';
export const ADD_CUSTOMER_SUCCESS = 'app/CustomerPage/ADD_CUSTOMER_SUCCESS';
export const ADD_CUSTOMER_ERROR = 'app/CustomerPage/ADD_CUSTOMER_ERROR';

export const GET_CUSTOMER_EDITTING = 'app/CustomerPage/GET_CUSTOMER_EDITTING';
export const GET_CUSTOMER_EDITTING_SUCCESS =
  'app/CustomerPage/GET_CUSTOMER_EDITTING_SUCCESS';
export const GET_CUSTOMER_EDITTING_ERROR =
  'app/CustomerPage/GET_CUSTOMER_EDITTING_ERROR';

export const EDIT_CUSTOMER = 'app/CustomerPage/EDIT_CUSTOMER';
export const EDIT_CUSTOMER_SUCCESS = 'app/CustomerPage/EDIT_CUSTOMER_SUCCESS';
export const EDIT_CUSTOMER_ERROR = 'app/CustomerPage/EDIT_CUSTOMER_ERROR';

export const GET_OPTIONS_CITY_WAREHOUSE_ADDRESS =
  'app/CustomerPage/GET_OPTIONS_CITY_WAREHOUSE_ADDRESS';

export const GET_OPTIONS_CITY_WAREHOUSE_ADDRESS_SUCCESS =
  'app/CustomerPage/GET_OPTIONS_CITY_WAREHOUSE_ADDRESS_SUCCESS';

export const GET_OPTIONS_CITY_WAREHOUSE_ADDRESS_ERROR =
  'app/CustomerPage/GET_OPTIONS_CITY_WAREHOUSE_ADDRESS_ERROR';

export const GET_OPTIONS_DISTRICT_WAREHOUSE_ADDRESS =
  'app/CustomerPage/GET_OPTIONS_DISTRICT_WAREHOUSE_ADDRESS';

export const GET_OPTIONS_DISTRICT_WAREHOUSE_ADDRESS_SUCCESS =
  'app/CustomerPage/GET_OPTIONS_DISTRICT_WAREHOUSE_ADDRESS_SUCCESS';

export const GET_OPTIONS_DISTRICT_WAREHOUSE_ADDRESS_ERROR =
  'app/CustomerPage/GET_OPTIONS_DISTRICT_WAREHOUSE_ADDRESS_ERROR';

export const GET_OPTIONS_WARD_WAREHOUSE_ADDRESS =
  'app/CustomerPage/GET_OPTIONS_WARD_WAREHOUSE_ADDRESS';

export const GET_OPTIONS_WARD_WAREHOUSE_ADDRESS_SUCCESS =
  'app/CustomerPage/GET_OPTIONS_WARD_WAREHOUSE_ADDRESS_SUCCESS';

export const GET_OPTIONS_WARD_WAREHOUSE_ADDRESS_ERROR =
  'app/CustomerPage/GET_OPTIONS_WARD_WAREHOUSE_ADDRESS_ERROR';

export const ADD_WAREHOUSE_ADDRESS = 'app/CustomerPage/ADD_WAREHOUSE_ADDRESS';
export const ADD_WAREHOUSE_ADDRESS_SUCCESS =
  'app/CustomerPage/ADD_WAREHOUSE_ADDRESS_SUCCESS';
export const ADD_WAREHOUSE_ADDRESS_ERROR =
  'app/CustomerPage/ADD_WAREHOUSE_ADDRESS_ERROR';

export const GET_LIST_WAREHOUSE_ADDRESS =
  'app/CustomerPage/GET_LIST_WAREHOUSE_ADDRESS';
export const GET_LIST_WAREHOUSE_ADDRESS_SUCCESS =
  'app/CustomerPage/GET_LIST_WAREHOUSE_ADDRESS_SUCCESS';
export const GET_LIST_WAREHOUSE_ADDRESS_ERROR =
  'app/CustomerPage/GET_LIST_WAREHOUSE_ADDRESS_ERROR';

export const EDIT_WAREHOUSE_ADDRESS = 'app/CustomerPage/EDIT_WAREHOUSE_ADDRESS';
export const EDIT_WAREHOUSE_ADDRESS_SUCCESS =
  'app/CustomerPage/EDIT_WAREHOUSE_ADDRESS_SUCCESS';
export const EDIT_WAREHOUSE_ADDRESS_ERROR =
  'app/CustomerPage/EDIT_WAREHOUSE_ADDRESS_ERROR';

export const DELETE_WAREHOUSE_ADDRESS =
  'app/CustomerPage/DELETE_WAREHOUSE_ADDRESS';
export const DELETE_WAREHOUSE_ADDRESS_SUCCESS =
  'app/CustomerPage/DELETE_WAREHOUSE_ADDRESS_SUCCESS';
export const DELETE_WAREHOUSE_ADDRESS_ERROR =
  'app/CustomerPage/DELETE_WAREHOUSE_ADDRESS_ERROR';
